CELL_SIZE = 32
LABEL_PADDING = 10
BOARD_SIZE = 19
PADDING = 30

LIGHT_BACKGROUND = "#FAEBD7"
SELECT_BACKGROUND = "#A68A64"
BORDER_COLOR = "#6f5c43"

BLACK_HOVER = "#666666"
WHITE_HOVER = "#EEEEEE"

LABEL_FONT = "Phosphate"
NAME_FONT = "Rockwell"
