# Etienne laptop
CELL_SIZE = 40
LABEL_PADDING = 10
BOARD_SIZE = 19
PADDING = 40
SETTING_PANEL_WIDTH = 400

# Yoonseo laptop
# CELL_SIZE = 30
# LABEL_PADDING = 10
# BOARD_SIZE = 19
# PADDING = 30
# SETTING_PANEL_WIDTH = 200


LIGHT_BACKGROUND = "#FAEBD7"
SELECT_BACKGROUND = "#A68A64"
BORDER_COLOR = "#6f5c43"

LABEL_FONT = "Phosphate"
NAME_FONT = "Rockwell"
