[package]
name = "lib_gomoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lib_gomoku"
path = "./src/lib.rs"
crate-type = ["cdylib", "rlib"]


[[bin]]
name = "gomoku-tester"
path = "./src/main.rs"

[profile.release]
debug = true

[dependencies]
pyo3 = "0.24.0"
ctrlc = "3"
signal-hook = "0.3.18"
linked_hash_set = "0.1.5"
colored = "3.0.0"
rayon = "1.10"
